name: Unused Deps

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Set up nightly toolchain
        uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e # nightly
        with:
          toolchain: nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@92e6dd1c202153a204d471a3c509bf1e03dcfa44 # v2
        with:
          tool: cargo-udeps

      - name: Run cargo-udeps (release, all targets)
        run: |
          cargo udeps --workspace --all-targets --all-features --release
