name: Unused Deps

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up nightly toolchain
        uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e # nightly
        with:
          toolchain: nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@50708e9ba8d7b6587a2cb575ddaa9a62e927bc06 # v2
        with:
          tool: cargo-udeps

      - name: Run cargo-udeps (release, all targets)
        run: |
          cargo udeps --workspace --all-targets --all-features --release
