name: Unused Deps

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up nightly toolchain
        uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # nightly
        with:
          toolchain: nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@8cd2ac21dc357ca7dd807fe294d11e9ef84f60ec # v2
        with:
          tool: cargo-udeps

      - name: Run cargo-udeps (release, all targets)
        run: |
          cargo udeps --workspace --all-targets --all-features --release
